name: Integração contínua

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - push-event
  workflow_dispatch: {}

jobs:
  multi-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checando repositório Main
        uses: actions/checkout@v3

      - name: Clonando repositório
        run: |
          git clone https://${{ secrets.TOKEN_REPOS }}@github.com/V8-PROJETO-RH/DEVOPS.git
        env:
          TOKEN_REPOS: ${{ secrets.TOKEN_REPOS }}
